chore(git-hooks): update `post-checkout` to change node version on difference of `.nvmrc`

diff --git a/.husky/post-checkout b/.husky/post-checkout
--- a/.husky/post-checkout
+++ b/.husky/post-checkout
@@ -17,81 +17,26 @@ fi
 
 # Function to configure git repository to enforce GPG signed commits
 config_git_commit_signing() {
-  if [ "$IS_CLONING" = "true" ]; then
-    log "Configuring Git: commit.gpgsign=true"
-    if ! git config --local commit.gpgsign true; then
-      error "ERROR: Failed to configure GPG signing for commits."
-      error "Commits are required to be signed for this repository."
-      exit 1
-    elif ! git config --get user.signingkey 1>/dev/null 2>&1; then
-      log "==============================================================="
-      log "                   USER ACTION REQUIRED!"
-      log "---------------------------------------------------------------"
-      log "GPG commit signing is required for this repository! Please"
-      log "configure your repository with the following command:"
-      log "" # prefixed-newline
-      log "    git config --local user.signingkey <GPG_KEY_ID>"
-      log "" # prefixed-newline
-      log "==============================================================="
-    fi
-    log "Signature exists: user.signingkey=$(git config --get user.signingkey)"
+  log "Configuring Git: commit.gpgsign=true"
+  if ! git config --local commit.gpgsign true; then
+    error "ERROR: Failed to configure GPG signing for commits."
+    error "Commits are required to be signed for this repository."
+    exit 1
+  elif ! git config --get user.signingkey 1>/dev/null 2>&1; then
+    log "==============================================================="
+    log "                   USER ACTION REQUIRED!"
+    log "---------------------------------------------------------------"
+    log "GPG commit signing is required for this repository! Please"
+    log "configure your repository with the following command:"
+    log "" # prefixed-newline
+    log "    git config --local user.signingkey <GPG_KEY_ID>"
+    log "" # prefixed-newline
+    log "==============================================================="
   fi
+  log "Signature exists: user.signingkey=$(git config --get user.signingkey)"
 }
 
-activate_nvm_env() {
-  # Only run if changing branches & NVM is installed
-  if ! [ "$CKOUT_TYPE_FLAG" = "1" ]; then
-    return 0 # Abort action
-  fi
-  if ! command -v nvm >/dev/null 2>&1; then
-    return 0 # Abort action
-  fi
-  output=""
-  if ! output=$(nvm use); then
-    if ! replay "$output" | grep --quiet "not yet installed"; then
-      unset output
-      return 0 # Abort action
-    fi
-    VERSION=""
-    VERSION="$(replay "$output" | grep 'nvm install' | sed 's/.*install v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')"
-    # enable user input, git by default runs in non-interactive mode
-    if ! exec </dev/tty; then
-      unset output VERSION
-      return 0 # Abort
-    fi
-    response=""
-    confirmed=false
-    while [ "$confirmed" = "false" ]; do
-      printf '%s' "Would you like to install Node.js ${VERSION} via nvm (Y/n)? "
-      read -r response;
-      if replay "$response" | grep -q -i -E '^\s*(Y|YES|YEP)\s*$'; then  
-        response="install"
-      elif replay "$response" | grep -q -i -E '^\s*(N|NO|NOPE)\s*$'; then
-        response=""
-      else
-        replay >&2 "Invalid response received. Try again."
-        continue
-      fi
-      confirmed=true;
-    done
-    if [ "$response" = "install" ]; then
-      log "Installing Node.js v$VERSION via nvm..."
-      if ! nvm install "$VERSION" --latest-npm; then
-        error "ERROR: nvm's installer failed, see error above."
-        error "Your node version does not match with the expected dev environment version."
-        unset output VERSION response confirmed
-        return 1
-      fi
-      log "node --version = $(node --version)"
-    else
-      error "NODE VERSION MIXMATCH: Expected dev environment Node.js version is not installed."
-      error "Authors expect to contributors to use the Node.js version defined in .nvmrc for development."
-      error "dev at your own risk!"
-    fi
-  fi
-  unset output VERSION response confirmed
-}
-
+# Function to update installed project dependencies based on changed package-lock.json
 update_npm_dependencies() {
   # Only run if changing branches and not performing the initial `git clone`
   if [ "$CKOUT_TYPE_FLAG" = "1" ] && [ "$IS_CLONING" = "false" ]; then
@@ -120,11 +65,25 @@ update_npm_dependencies() {
   fi
 }
 
-config_git_commit_signing
-activate_nvm_env
+# -----------------------------------------
+# main
+# -----------------------------------------
+# [1] 
+if [ "$IS_CLONING" = "true" ]; then
+  config_git_commit_signing
+fi
+
+# [2] Only run if changing branches
+if [ "$CKOUT_TYPE_FLAG" -eq 1 ] && ! activate_nvm_env; then
+  error "due to an error above, your npm dependencies were not updated automatically."
+  error "you will need to run 'npm install' yourself."
+  exit 1
+fi
+
+# [3]
 update_npm_dependencies
 
 # [4] env cleanup (vars, functions, utils)
 unset -v HEAD_PREV HEAD_NEW CKOUT_TYPE_FLAG IS_CLONING
-unset -f config_git_commit_signing activate_nvm_env update_npm_dependencies
+unset -f config_git_commit_signing update_npm_dependencies
 cleanup
