chore(git-hooks): convert back to posix-sh compliance & add env cleanup

diff --git a/.husky/post-checkout b/.husky/post-checkout
--- a/.husky/post-checkout
+++ b/.husky/post-checkout
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
 LOG_PREFIX="[.husky/post-checkout]"
@@ -16,13 +16,13 @@ if [ -z "$HEAD_PREV" ]; then
 fi
 
 config_git_commit_signing() {
-  if [ "$IS_CLONING" == true ]; then
+  if [ "$IS_CLONING" = "true" ]; then
     log "Configuring Git: commit.gpgsign=true"
     if ! git config --local commit.gpgsign true; then
       error "ERROR: Failed to configure GPG signing for commits."
       error "Commits are required to be signed for this repository."
       exit 1
-    elif ! git config --get user.signingkey &>/dev/null; then
+    elif ! git config --get user.signingkey 1>/dev/null 2>&1; then
       log "==============================================================="
       log "                   USER ACTION REQUIRED!"
       log "---------------------------------------------------------------"
@@ -39,8 +39,8 @@ config_git_commit_signing() {
 
 update_npm_dependencies() {
   # Only run if changing branches and not performing the initial `git clone`
-  if [ "$CKOUT_TYPE_FLAG" == 1 ] && [ "$IS_CLONING" == false ]; then
-    local changed_files=""
+  if [ "$CKOUT_TYPE_FLAG" = "1" ] && [ "$IS_CLONING" = "false" ]; then
+    changed_files=""
     # derived from https://gist.github.com/taurus227/28960de89e6c43bb3d492125368f1224
     changed_files="$(git diff-tree -r --name-only --diff-filter=M --no-commit-id "$HEAD_PREV" "$HEAD_NEW")"
 
@@ -48,7 +48,7 @@ update_npm_dependencies() {
       log "CHANGE DETECTED: 'package-lock.json'"
       log "Dependency requirements changed! This will take a few seconds..."
 
-      if ! command -v npm &>/dev/null; then
+      if ! command -v npm 1>/dev/null 2>&1; then
         log "NPM not found on \$PATH, however 'npm install' is desired. Please accomplish manually."
         return 1
       fi
@@ -59,8 +59,14 @@ update_npm_dependencies() {
         return 1
       fi
     fi
+    unset changed_files
   fi
 }
 
 config_git_commit_signing
 update_npm_dependencies
+
+# env cleanup (vars, functions, utils)
+unset HEAD_PREV HEAD_NEW CKOUT_TYPE_FLAG IS_CLONING
+unset config_git_commit_signing activate_nvm_env update_npm_dependencies
+cleanup
diff --git a/.husky/post-merge b/.husky/post-merge
--- a/.husky/post-merge
+++ b/.husky/post-merge
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
 [ -z "$LOG_PREFIX" ] && LOG_PREFIX="[.husky/post-merge]"
@@ -7,10 +7,10 @@
 
 update_npm_dependencies() {
   # derived from https://gist.github.com/taurus227/28960de89e6c43bb3d492125368f1224
-  local changed_files=""
-  local output=""
-  local lockfiles=()
-  local NEEDS_INSTALL=true
+  changed_files=""
+  output=""
+  lockfiles=""
+  NEEDS_INSTALL=true
 
   changed_files="$(git diff-tree -r --name-only --diff-filter=M --no-commit-id ORIG_HEAD HEAD)"
 
@@ -18,8 +18,14 @@ update_npm_dependencies() {
     log "CHANGE DETECTED: 'package-lock.json'"
     log "Lock files rarely merge properly. Deleting and re-generating it..."
 
-    lockfiles=("$output")            # make array of filepaths
-    rm "${lockfiles[@]}"
+    # concatenate filenames with space (collapse newlines)
+    if ! lockfiles="$(printf '%s' "$output" | tr '\n' ' ')"; then
+      error "ERROR: something bad happened. Exiting..."
+      unset changed_files output lockfiles NEEDS_INSTALL
+      return 1
+    fi
+
+    rm "$lockfiles"
 
   elif replay "$changed_files" | grep --quiet "package.json"; then
     log "CHANGE DETECTED: 'package.json'"
@@ -28,15 +34,19 @@ update_npm_dependencies() {
     NEEDS_INSTALL=false
   fi
 
-  if [ "$NEEDS_INSTALL" == true ]; then
-    if ! command -v npm &>/dev/null; then
+  if [ "$NEEDS_INSTALL" = "true" ]; then
+    unset NEEDS_INSTALL
+
+    if ! command -v npm 1>/dev/null 2>&1; then
       error "ERROR: NPM not found on \$PATH, however 'npm install' is desired. Please accomplish manually."
+      unset changed_files output lockfiles
       return 1
     fi
 
     if ! explicit_run_cmd "npm install --prefer-offline --no-fund --no-audit"; then
       error "ERROR: Dependency installation failed."
       error "You will need to perform an install manually to continue."
+      unset changed_files output lockfiles
       return 1
     fi
 
@@ -44,20 +54,43 @@ update_npm_dependencies() {
     if output="$(replay "$changed_files" | grep "package-lock.json")"; then
       log "ALL FIXED! package-lock.json needed a refresh."
 
-      lockfiles=("$output")            # make array of filepaths
-      git add -- "${lockfiles[@]}"
-      
-      for lockfile in "${lockfiles[@]}"; do
-        log "STAGED: $lockfile"
-      done
-      
-      local filenoun="file"
-      if [ "${#lockfiles[@]}" -gt 1 ]; then
+      # concatenate filenames with space (collapse newlines)
+      if ! lockfiles="$(printf '%s' "$output" | tr '\n' ' ')"; then
+        error "ERROR: something bad happened. Exiting..."
+        unset changed_files output lockfiles
+        return 1
+      fi
+
+      if ! eval "git add -- $lockfiles"; then
+        error "ERROR: some reason git failed.  Exiting..."
+        unset changed_files output lockfiles
+        return 1
+      fi
+
+      count=0
+      tmp="$(mktmp)"
+      replay "$output" > "$tmp"
+      while IFS= read -r line <&3 || [ -n "$line" ]; do
+        {
+          log "STAGED: $line" || break # abort upon failure if relevant
+          count=$((count+1))
+        } 3<&-
+      done 3< "$tmp"
+      rm "$tmp"
+
+      filenoun="file"
+      if [ $count -gt 1 ]; then
         filenoun="${filenoun}s"
       fi
       log "Please commit the newly generated $filenoun for the team!"
+      unset count filenoun
     fi
   fi
+  unset changed_files output lockfiles NEEDS_INSTALL
 }
 
 update_npm_dependencies
+
+# env cleanup (vars, functions, utils)
+unset update_npm_dependencies
+cleanup
