chore(git-hooks): shellcheck corrections & fixed missing error checking in `post-checkout` hook

diff --git a/.husky/post-checkout b/.husky/post-checkout
--- a/.husky/post-checkout
+++ b/.husky/post-checkout
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 . "$(dirname "$0")/_/husky.sh"
 
 LOG_PREFIX="[.husky/post-checkout]"
@@ -8,12 +8,15 @@ LOG_PREFIX="[.husky/post-checkout]"
 HEAD_PREV="$1"
 HEAD_NEW="$2"
 CKOUT_TYPE_FLAG="$3"      # 0 = retrieve file from index, 1 = changing branches
+IS_CLONING=false
 
 # check if this is a post-checkout after a `git clone`
-IS_CLONING=$( [ -z "$HEAD_PREV" ] && echo true || echo false )
+if [ -z "$HEAD_PREV" ]; then
+  IS_CLONING=true
+fi
 
 config_git_commit_signing() {
-  if [ $IS_CLONING == true ]; then
+  if [ "$IS_CLONING" == true ]; then
     log "Configuring Git: commit.gpgsign=true"
     if ! git config --local commit.gpgsign true; then
       error "ERROR: Failed to configure GPG signing for commits."
@@ -36,22 +39,25 @@ config_git_commit_signing() {
 
 update_npm_dependencies() {
   # Only run if changing branches and not performing the initial `git clone`
-  if [ $CKOUT_TYPE_FLAG == 1 ] && [ $IS_CLONING == false ]; then
+  if [ "$CKOUT_TYPE_FLAG" == 1 ] && [ "$IS_CLONING" == false ]; then
     local changed_files=""
     # derived from https://gist.github.com/taurus227/28960de89e6c43bb3d492125368f1224
-    changed_files="$(git diff-tree -r --name-only --diff-filter=M --no-commit-id $HEAD_PREV $HEAD_NEW)"
+    changed_files="$(git diff-tree -r --name-only --diff-filter=M --no-commit-id "$HEAD_PREV" "$HEAD_NEW")"
 
     if echo "$changed_files" | grep --quiet "package-lock.json"; then
       log "CHANGE DETECTED: 'package-lock.json'"
       log "Dependency requirements changed! This will take a few seconds..."
 
-      local cmd="npm install --prefer-offline --no-fund --no-audit"
       if ! command -v npm &>/dev/null; then
-        log "NPM not found on \$PATH, however '$cmd' is desired. Please accomplish manually."
-        return
+        log "NPM not found on \$PATH, however 'npm install' is desired. Please accomplish manually."
+        return 1
       fi
-      log "$> $cmd"
-      eval "$cmd"
+
+      if ! explicit_run_cmd "npm install --prefer-offline --no-fund --no-audit"; then
+        error "ERROR: Dependency installation failed."
+        error "You will need to perform an install manually to continue."
+        return 1
+      fi
     fi
   fi
 }
