feat-dev: Improv lint precommit msg & flow

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,15 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npm run lint
+export NODE_ENV=production
+
+LOG_PREFIX="[.husky/pre-commit]"
+
+. "$(dirname "$0")/hook-utils.sh"
+
+log "$> npm run lint"
+if ! npm run lint; then
+  error "ERROR: Dirty code detected!"
+  error "Fix the lint errors before committing to the repository."
+  exit -1
+fi
